
server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      # routes:
      #   - id: user-service
      #     uri: lb://USER-SERVICE
      #     predicates:
      #      - Path=/api/users/**

      #   - id: book-service
      #     uri: lb://BOOK-SERVICE
      #     predicates:
      #       - Path=/api/books/**

      #   - id: order-service
      #     uri: lb://ORDER-SERVICE
      #     predicates:
      #       - Path=/api/orders/**
            
      #   - id: auth-service
      #     uri: lb://AUTH-SERVICE
      #     predicates:
      #       - Path=/api/auths/**
        

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
