server:
  port: 8085

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/payments_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "2004"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
